### ISSUE TITLE
Where can I find the pubkey for the server ?

### ISSUE THREAD

**Issue by ultrainstintgoku** [oxen-io/session-push-notification-server#15]
I try to run the Push Notification server , But Cant Able to find the Pubkey

**Comment by RyanRory** [comment]
Hi @ultrainstintgoku, thanks for reaching out. You may want to create your own x25519 key pair so you can run the server. And you need your own apple push service certificate to make the server work. :)

**Comment by RyanRory** [comment]
You can use a python script to generate the key pair, here is an example:

```
    random = get_random_bytes(32)                      # The private key 32 bytes
    priv = _curve25519.make_private(random)
    print(priv.hex())
    pub = _curve25519.make_public(priv)
    print(pub.hex())
```

I'll update the README to include this info.

**Comment by martin-braun** [comment]
@RyanRory Why does `oxend` not create a public key called `key_ed25519.pub` on launch instead? This is unnecessary complexity on the end-user. 

For anybody else finding this: `enigma-sn-keys generate FILENAME` generates a new private key while printing the public key.

**Comment by martin-braun** [comment]
@RyanRory Why does `oxend` not create a public key called `key_ed25519.pub` on launch instead? This is unnecessary complexity on the end-user. 

For anybody else finding this: `oxend-sn-keys generate FILENAME` generates a new private key while printing the public key.
