### ISSUE TITLE
Suggest to loosen the dependency on telepot

### ISSUE THREAD

**Issue by Agnes-U** [oxen-io/session-push-notification-server#21]
Hi, your project session-push-notification-server(commit id: 9d495fdc8b1a237fa6ffda1b00c64a439f9941c9) requires "telepot==12.7" in its dependency. After analyzing the source code, we found that the following versions of telepot can also be suitable, i.e., telepot 12.0, 12.1, 12.2, 12.3, 12.4, 12.5, 12.6, since all functions that you directly (3 APIs: telepot.loop.MessageLoop.__init__, telepot.__init__.glance, telepot.__init__.Bot.__init__) or indirectly (propagate to 7 telepot's internal APIs and 1 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on telepot from "telepot==12.7" to "telepot>=12.0,<=12.7". This will improve the applicability of session-push-notification-server and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on telepot?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by jagerman** [comment]
Closing; with v2 we no longer have a bot attached for monitoring.
