### ISSUE TITLE
Any update for this project ? and /loki/v2/lsrpc not found...

### ISSUE THREAD

**Issue by babyfish0226** [oxen-io/session-push-notification-server#7]
I had made the session-push-notification-server working on server. But when i try to test the version from 1.60 to 1.65 of session-ios . All can't work.  for example, not found "/loki/v2/lsrpc" in server.py and register the device always not work.

Which version of session-ios will fit this notification server ? or any plan to upate? Thanks.

**Comment by RyanRory** [comment]
We just updated this repo and we'll keep maintaining this. Now you can find the `/loki/v2/lsrpc` endpoint in `master` branch. Cheers.
